/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminQueueRouteImport } from './routes/admin/queue'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppHelpRouteImport } from './routes/app/help'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppPreferencesRouteImport } from './routes/app/preferences'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppSavedRouteImport } from './routes/app/saved'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffAvailabilityRouteImport } from './routes/staff/availability'
import { Route as StaffCalendarRouteImport } from './routes/staff/calendar'
import { Route as StaffMoreRouteImport } from './routes/staff/more'
import { Route as StaffNotificationsRouteImport } from './routes/staff/notifications'
import { Route as StaffProfileRouteImport } from './routes/staff/profile'
import { Route as StaffQueueRouteImport } from './routes/staff/queue'
import { Route as StaffWalkInRouteImport } from './routes/staff/walk-in'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers/$id'
import { Route as AdminStaffIndexRouteImport } from './routes/admin/staff/index'
import { Route as AdminStaffIdRouteImport } from './routes/admin/staff/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as AppAppointmentsIndexRouteImport } from './routes/app/appointments/index'
import { Route as AppAppointmentsIdRouteImport } from './routes/app/appointments/$id'
import { Route as AppBookIndexRouteImport } from './routes/app/book/index'
import { Route as AppBookSuccessRouteImport } from './routes/app/book/success'
import { Route as AppServicesIndexRouteImport } from './routes/app/services/index'
import { Route as AppServicesServiceIdRouteImport } from './routes/app/services/$serviceId'
import { Route as StaffAppointmentsIdRouteImport } from './routes/staff/appointments/$id'
import { Route as StaffCustomersIndexRouteImport } from './routes/staff/customers/index'
import { Route as StaffCustomersIdRouteImport } from './routes/staff/customers/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRouteRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffAvailabilityRoute = StaffAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCalendarRoute = StaffCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffMoreRoute = StaffMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffWalkInRoute = StaffWalkInRouteImport.update({
  id: '/walk-in',
  path: '/walk-in',
  getParentRoute: () => StaffRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIdRoute = AdminStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppointmentsIdRoute = AppAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookIndexRoute = AppBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookSuccessRoute = AppBookSuccessRouteImport.update({
  id: '/book/success',
  path: '/book/success',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicesServiceIdRoute = AppServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => AppRouteRoute,
} as any)
const StaffAppointmentsIdRoute = StaffAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCustomersIndexRoute = StaffCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCustomersIdRoute = StaffCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => StaffRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/enter': typeof EnterRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/help': typeof AppHelpRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/saved': typeof AppSavedRoute
  '/staff/availability': typeof StaffAvailabilityRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/more': typeof StaffMoreRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/walk-in': typeof StaffWalkInRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
  '/app/book/success': typeof AppBookSuccessRoute
  '/app/services/$serviceId': typeof AppServicesServiceIdRoute
  '/staff/appointments/$id': typeof StaffAppointmentsIdRoute
  '/staff/customers/$id': typeof StaffCustomersIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/app/appointments/': typeof AppAppointmentsIndexRoute
  '/app/book/': typeof AppBookIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/staff/customers/': typeof StaffCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enter': typeof EnterRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/help': typeof AppHelpRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/saved': typeof AppSavedRoute
  '/staff/availability': typeof StaffAvailabilityRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/more': typeof StaffMoreRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/walk-in': typeof StaffWalkInRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
  '/app/book/success': typeof AppBookSuccessRoute
  '/app/services/$serviceId': typeof AppServicesServiceIdRoute
  '/staff/appointments/$id': typeof StaffAppointmentsIdRoute
  '/staff/customers/$id': typeof StaffCustomersIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
  '/app/book': typeof AppBookIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/staff/customers': typeof StaffCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/enter': typeof EnterRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/help': typeof AppHelpRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/saved': typeof AppSavedRoute
  '/staff/availability': typeof StaffAvailabilityRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/more': typeof StaffMoreRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/walk-in': typeof StaffWalkInRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
  '/app/book/success': typeof AppBookSuccessRoute
  '/app/services/$serviceId': typeof AppServicesServiceIdRoute
  '/staff/appointments/$id': typeof StaffAppointmentsIdRoute
  '/staff/customers/$id': typeof StaffCustomersIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/app/appointments/': typeof AppAppointmentsIndexRoute
  '/app/book/': typeof AppBookIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/staff/customers/': typeof StaffCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/staff'
    | '/enter'
    | '/login'
    | '/setup'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/gallery'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/app/activity'
    | '/app/help'
    | '/app/notifications'
    | '/app/payments'
    | '/app/preferences'
    | '/app/profile'
    | '/app/saved'
    | '/staff/availability'
    | '/staff/calendar'
    | '/staff/more'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/queue'
    | '/staff/walk-in'
    | '/admin/'
    | '/app/'
    | '/staff/'
    | '/admin/customers/$id'
    | '/admin/staff/$id'
    | '/api/auth/$'
    | '/api/payments/webhook'
    | '/app/appointments/$id'
    | '/app/book/success'
    | '/app/services/$serviceId'
    | '/staff/appointments/$id'
    | '/staff/customers/$id'
    | '/admin/customers/'
    | '/admin/staff/'
    | '/app/appointments/'
    | '/app/book/'
    | '/app/services/'
    | '/staff/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enter'
    | '/login'
    | '/setup'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/gallery'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/app/activity'
    | '/app/help'
    | '/app/notifications'
    | '/app/payments'
    | '/app/preferences'
    | '/app/profile'
    | '/app/saved'
    | '/staff/availability'
    | '/staff/calendar'
    | '/staff/more'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/queue'
    | '/staff/walk-in'
    | '/admin'
    | '/app'
    | '/staff'
    | '/admin/customers/$id'
    | '/admin/staff/$id'
    | '/api/auth/$'
    | '/api/payments/webhook'
    | '/app/appointments/$id'
    | '/app/book/success'
    | '/app/services/$serviceId'
    | '/staff/appointments/$id'
    | '/staff/customers/$id'
    | '/admin/customers'
    | '/admin/staff'
    | '/app/appointments'
    | '/app/book'
    | '/app/services'
    | '/staff/customers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/staff'
    | '/enter'
    | '/login'
    | '/setup'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/gallery'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/app/activity'
    | '/app/help'
    | '/app/notifications'
    | '/app/payments'
    | '/app/preferences'
    | '/app/profile'
    | '/app/saved'
    | '/staff/availability'
    | '/staff/calendar'
    | '/staff/more'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/queue'
    | '/staff/walk-in'
    | '/admin/'
    | '/app/'
    | '/staff/'
    | '/admin/customers/$id'
    | '/admin/staff/$id'
    | '/api/auth/$'
    | '/api/payments/webhook'
    | '/app/appointments/$id'
    | '/app/book/success'
    | '/app/services/$serviceId'
    | '/staff/appointments/$id'
    | '/staff/customers/$id'
    | '/admin/customers/'
    | '/admin/staff/'
    | '/app/appointments/'
    | '/app/book/'
    | '/app/services/'
    | '/staff/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  EnterRoute: typeof EnterRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/preferences': {
      id: '/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/saved': {
      id: '/app/saved'
      path: '/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/availability': {
      id: '/staff/availability'
      path: '/availability'
      fullPath: '/staff/availability'
      preLoaderRoute: typeof StaffAvailabilityRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/calendar': {
      id: '/staff/calendar'
      path: '/calendar'
      fullPath: '/staff/calendar'
      preLoaderRoute: typeof StaffCalendarRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/more': {
      id: '/staff/more'
      path: '/more'
      fullPath: '/staff/more'
      preLoaderRoute: typeof StaffMoreRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/queue': {
      id: '/staff/queue'
      path: '/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/walk-in': {
      id: '/staff/walk-in'
      path: '/walk-in'
      fullPath: '/staff/walk-in'
      preLoaderRoute: typeof StaffWalkInRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/$id': {
      id: '/admin/staff/$id'
      path: '/staff/$id'
      fullPath: '/admin/staff/$id'
      preLoaderRoute: typeof AdminStaffIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/appointments/': {
      id: '/app/appointments/'
      path: '/appointments'
      fullPath: '/app/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/appointments/$id': {
      id: '/app/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/app/appointments/$id'
      preLoaderRoute: typeof AppAppointmentsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book/': {
      id: '/app/book/'
      path: '/book'
      fullPath: '/app/book/'
      preLoaderRoute: typeof AppBookIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book/success': {
      id: '/app/book/success'
      path: '/book/success'
      fullPath: '/app/book/success'
      preLoaderRoute: typeof AppBookSuccessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/services/$serviceId': {
      id: '/app/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/app/services/$serviceId'
      preLoaderRoute: typeof AppServicesServiceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/staff/appointments/$id': {
      id: '/staff/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/staff/appointments/$id'
      preLoaderRoute: typeof StaffAppointmentsIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/customers/': {
      id: '/staff/customers/'
      path: '/customers'
      fullPath: '/staff/customers/'
      preLoaderRoute: typeof StaffCustomersIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/customers/$id': {
      id: '/staff/customers/$id'
      path: '/customers/$id'
      fullPath: '/staff/customers/$id'
      preLoaderRoute: typeof StaffCustomersIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminStaffIdRoute: typeof AdminStaffIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminStaffIdRoute: AdminStaffIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppHelpRoute: typeof AppHelpRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppointmentsIdRoute: typeof AppAppointmentsIdRoute
  AppBookSuccessRoute: typeof AppBookSuccessRoute
  AppServicesServiceIdRoute: typeof AppServicesServiceIdRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppBookIndexRoute: typeof AppBookIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppHelpRoute: AppHelpRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppointmentsIdRoute: AppAppointmentsIdRoute,
  AppBookSuccessRoute: AppBookSuccessRoute,
  AppServicesServiceIdRoute: AppServicesServiceIdRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppBookIndexRoute: AppBookIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffAvailabilityRoute: typeof StaffAvailabilityRoute
  StaffCalendarRoute: typeof StaffCalendarRoute
  StaffMoreRoute: typeof StaffMoreRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffQueueRoute: typeof StaffQueueRoute
  StaffWalkInRoute: typeof StaffWalkInRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffAppointmentsIdRoute: typeof StaffAppointmentsIdRoute
  StaffCustomersIdRoute: typeof StaffCustomersIdRoute
  StaffCustomersIndexRoute: typeof StaffCustomersIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffAvailabilityRoute: StaffAvailabilityRoute,
  StaffCalendarRoute: StaffCalendarRoute,
  StaffMoreRoute: StaffMoreRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffQueueRoute: StaffQueueRoute,
  StaffWalkInRoute: StaffWalkInRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffAppointmentsIdRoute: StaffAppointmentsIdRoute,
  StaffCustomersIdRoute: StaffCustomersIdRoute,
  StaffCustomersIndexRoute: StaffCustomersIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  EnterRoute: EnterRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
